// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG3EiA2iVjnrZzT5A7ufpefvcwh5Ng0Pw',
    appId: '1:422358209937:web:36c3e95691a905e65d7630',
    messagingSenderId: '422358209937',
    projectId: 'epn360-e218b',
    authDomain: 'epn360-e218b.firebaseapp.com',
    storageBucket: 'epn360-e218b.firebasestorage.app',
    measurementId: 'G-9018JD0Q83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv__jkOTRR1tEg49mikdQ2wMYvtPMCZcE',
    appId: '1:422358209937:android:c650a056cc3dc53f5d7630',
    messagingSenderId: '422358209937',
    projectId: 'epn360-e218b',
    storageBucket: 'epn360-e218b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvRtI7H99pwusaM64apMqQimBtvZ1H98Q',
    appId: '1:422358209937:ios:b761ba9d4fa87b705d7630',
    messagingSenderId: '422358209937',
    projectId: 'epn360-e218b',
    storageBucket: 'epn360-e218b.firebasestorage.app',
    iosBundleId: 'com.example.epn360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG3EiA2iVjnrZzT5A7ufpefvcwh5Ng0Pw',
    appId: '1:422358209937:web:bf22494dc64d26c85d7630',
    messagingSenderId: '422358209937',
    projectId: 'epn360-e218b',
    authDomain: 'epn360-e218b.firebaseapp.com',
    storageBucket: 'epn360-e218b.firebasestorage.app',
    measurementId: 'G-0PSSEJ3PNZ',
  );
}
